name: gezzy_buddy
description: A travel planning application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_analytics: ^10.7.4
  firebase_storage: ^11.5.6
  cloud_firestore: ^4.13.6
  google_sign_in: ^6.1.6
  provider: ^6.1.1
  http: ^0.13.3
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  google_maps_flutter: ^2.5.0
  location: ^5.0.3
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  intl: ^0.19.0
  path_provider: ^2.1.1
  image_picker: ^1.0.4
  url_launcher: ^6.2.2
  share_plus: ^7.2.1
  flutter_dotenv: ^5.1.0
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  crypto: ^3.0.3
  pdf: ^3.8.4
  csv: ^5.1.1
  flutter_lints: ^3.0.1
  google_fonts: ^4.0.4
  google_place: ^0.4.7
  flutter_polyline_points: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  freezed: ^2.4.1
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/plaj.png
    - assets/images/kulturel.png
    - assets/images/
    - assets/icons/
    - .env

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/splash.png"
  android: true
  ios: true

flutter_intl:
  enabled: true
  class_name: AppLocalizations
  main_locale: tr
  arb_dir: lib/l10n
  output_dir: lib/generated
  use_deferred_loading: false 